dist: focal

language: cpp

compiler:
  - gcc

sudo: required

before_install:
  - sudo apt update
  - sudo apt remove --purge cmake
  - sudo apt install libboost-all-dev

script:
  - ./build_linux_osx.sh
  - ./build/algorithm-cpp

notifications:
  slack: vincentselfworkspace:RwkrpoJGclmeDDvddB5Hxz01
